name: Dart CI

on:
  push:
    branches: [ main, 2.x, 1.x ]
  pull_request:
    branches: [ main, 2.x, 1.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Dart Action
      uses: cedx/setup-dart@v2.2.0
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test -p chrome,vm
